# Generated by Django 4.1.5 on 2023-01-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=9)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.data')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=9)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.day')),
            ],
        ),
    ]
