# Generated by Django 4.1.5 on 2023-03-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_data_day_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
